### ISSUE TITLE
Fixed size for the main container doesn't allow for wrapping text.

### ISSUE THREAD

**Issue by harlanhaskins** [fedora-infra/asknot-ng#7]
Here's a screenshot:

![screen shot 2015-02-05 at 12 16 40 pm](https://cloud.githubusercontent.com/assets/853032/6065146/f293efe8-ad30-11e4-8973-258875fc902b.png)

``` css
.bandana {
    height: 200px;
    // ...
}
```
